export const SITE = {
  website: "https://planadesu.github.io/",
  author: "Plana",
  profile: "https://github.com/planadesu",
  desc: "欢迎访问 Plana 的个人笔记！",
  title: "Plana笔记",
  ogImage: "og.png",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: true,
    text: "编辑",
    url: "https://github.com/planadesu/notes/edit/master/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "zh-CN",
  timezone: "Asia/Shanghai",
} as const;
